### ISSUE TITLE
Course6: Advanced React final project

### ISSUE THREAD

**Issue by naser2884** [joanskenderi/Meta-Front-End-Developer-Professional-Certificate#2]
Hello my friend

I am sorry for inconvenience, can u upload final project? I want to pass this course 

pls bro.

Nasser

**Comment by joanskenderi** [comment]
Hello Nasser,
I believe that the project will be pushed by the end of the weekend.
Joan

**Comment by naser2884** [comment]
thank u

**Comment by joanskenderi** [comment]
Hello Nasser,
The final project is finally pushed! Remember that copying the code and not coming up with your own solution is against Coursera's **_Honour Code_**. Other than that I wish you the best of luck.
Joan
