### ISSUE TITLE
Course7: Principles of UX/UI Design

### ISSUE THREAD

**Issue by naser2884** [joanskenderi/Meta-Front-End-Developer-Professional-Certificate#3]
Hello my friend

I am sorry for inconvenience, can u upload week 4 and week 5 (final project) of Principles of UX/UI Design course? 

pls bro.

Nasser

**Comment by naser2884** [comment]
Many thanks of uploading Course 6

**Comment by joanskenderi** [comment]
Hello Nasser,
I will push the solutions in this order Capstone, Advanced React, HTML and CSS in depth, and then UX/UI (if the final course isn't out yet). I prioritise more coding than the designing, but don't worry I will try to push everything ASAP :)
